services:
  l2_api:
    build: .
    container_name: l2_api
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      l2_db:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
        npm ci --legacy-peer-deps &&
        npm run test -- --runInBand &&
        npm run typeorm:migration:run:prod &&
        npm run start:prod
      "

  l2_db:
    image: postgres:15
    container_name: l2_nest_db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
